### ISSUE TITLE
Pre-populate Grpc Request parameters using Protobuf fields and types definition 

### ISSUE THREAD

**Issue by tiero** [singnet/snet-betav1-dapp#129]
**Is your feature request related to a problem? Please describe.**
Asking the end user of the dapp to fetch the protobuf and figure out by himself to fill the input JSON it adds a lot of friction

**Describe the solution you'd like**
Having the name of the field and his type in the Protobuf message defined by the rpc service, we should generate the html input needed by the type (eg. int => <input type="number" />)
and pre fill with the relative zero value.

The result should be parsed as well

**Describe alternatives you've considered**
We have protobuf for this exact reason

![screen shot 2019-02-10 at 14 49 56](https://user-images.githubusercontent.com/3596602/52534552-45494800-2d43-11e9-8c01-31ab4d09c995.png)

**Comment by ferrouswheel** [comment]
I agree that it could be done nicer and we should make the spec visible to the user without forcing them to look it up.

However it's complicated by the fact that protobuf can have nested message types and isn't just a list of key-values. It also needs to support repeated fields, either/or sections (the `oneof` keyword), and other parts of the protocol buffer specs...

**Comment by tiero** [comment]
> I agree that it could be done nicer and we should make the spec visible to the user without forcing them to look it up.
> 
> However it's complicated by the fact that protobuf can have nested message types and isn't just a list of key-values. It also needs to support repeated fields, either/or sections (the `oneof` keyword), and other parts of the protocol buffer specs...

Agreed.

I would roll-out the auto-generation for simple cases first (eg. no nested types and repeated) and then support gradually the whole scenario.
