### ISSUE TITLE
After using a service, I cannot reuse the channel balance but I'm "forced" to "Reserve Funds" to go forward in launching another invoke 

### ISSUE THREAD

**Issue by tiero** [singnet/snet-betav1-dapp#132]
**Describe the bug**
After using a service, I cannot reuse the channel balance but I'm "forced" to "Reserve Funds" to go forward in launching another invoke 

**To Reproduce**
1. Go to 'http://beta.singularitynet.io'
2. Click on Example1 - Calculator
3. Start Job
4. Reserve funds
5. Invoke service
6. See the result
7. Now, you cannot go back again to invoke. Only FUND is available
8. If you go to FUND it allows opening a new channel with the same provider

**Expected behavior**
Once I used first time the service, I want to go back to Invoke tab and call it again

**Desktop (please complete the following information):**
 - OS: MACOSX
 - Browser Firefox
 - Version 65

**Comment by raamb** [comment]
WITH PR #131 we reuse channels where possible. You can now fund a channel with enough tokens to allow for reuse, without having to create a new channel on every invocation
