### ISSUE TITLE
[Ropsten] Account page - Channels details not shown

### ISSUE THREAD

**Issue by tiero** [singnet/snet-betav1-dapp#133]
**Describe the bug**
After opening multiple channels, no channel is shown in Account > Channel Details page

**To Reproduce**
1. Go to 'http://beta.singularitynet.io'
2. Deposit
3. Select a service and Start Job
4. Reserve funds
5. Invoke
6. Repeat this multiple services
7. Then go to Account page
8. See the channel detail box blank

**Expected behavior**
List of opened channels 

**Screenshots**

![screen shot 2019-02-10 at 15 14 13](https://user-images.githubusercontent.com/3596602/52534820-8a22ae00-2d46-11e9-9e31-69206f85bec0.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Firefox
 - Version 65

**Comment by ferrouswheel** [comment]
I've noticed that channels have shown up when they have expired, letting me claim the expired funds...

![image](https://user-images.githubusercontent.com/120327/52541545-36be6780-2dfb-11e9-8695-936e30ec344f.png)

If it's intended to only show expired channels we should make it clearer in the UI. I also think it'd be worth making expired and active channels look visually different, or placed in different tables.

**Comment by raamb** [comment]
This table will only display expired channels. The heading has been updated to indicate the same.
