### ISSUE TITLE
Expiration should be more user friendly: relative and in days!

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-betav1-dapp#192]
I would propose to make "expiration" more user friendly. 
- It should be relative, not absolute. 
- It should be in days not in block-numbers.

I propose the following design:  Instead of one field "Expiry Blocknumber" I propose to have  two "connected" fields (if user edits one then the content of the other one is changing automatically).
Two fields:
 - "Relative expiration in blocks" which show: ```expiration - current_block```
- "Relative expiration in days"  which show expiration in days assuming 15 second block (with asterisks which explain it): ```(expiration - current_block)*5760```

Actually for dApp we could even go with one field: relative expiration in days.

**Comment by Vivek205** [comment]
Datepicker is added for selecting expiration.
