### ISSUE TITLE
UI components are not registered per network

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-betav1-dapp#203]
We make an assumption in ServiceMapping.js that services will have the same org and name on every network. This won't necessarily be the case.

Action ServiceMapping should be improved to do maintain a separate mapping for each network.

Ideally done in a way so developers only have to specify them for each network if they are different, otherwise they can specify the same mapping for all.

**Comment by Vivek205** [comment]
Issue FIxed #234.
