### ISSUE TITLE
Search shows nothing if viewing second page

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-betav1-dapp#224]
Changing the search term should reset the current page of results to page 1.

Currently if I go to page 2 of all services, then search for "face" I see nothing.

If I go to page 1 of all services, then search for "face" I see the services I was expecting.

**Comment by Vivek205** [comment]
will be fixed along with the issue #77

**Comment by ferrouswheel** [comment]
Ideally we'd fix something and then close the issue - not close it and promise it will eventually be fixed.
