### ISSUE TITLE
The winter wonderland and it's magical elves

### ISSUE THREAD

**Issue by w1kke** [singnet/snet-betav1-dapp#227]
There once was the winter wonderland and in it there was a large group of elves. They were really magical as they could melt the snow and grow food.

**Comment by pennachin** [comment]
I believe the community forums are the right place to discuss this, as it's not a software issue.

**Comment by w1kke** [comment]
I opened this issue because @IbbyBenali told me to open it here.

**Comment by pennachin** [comment]
Understood, and this is an important topic, I don't want to sound dismissive. It's not a software issue, though, which is why we should discuss it elsewhere.

**Comment by IbbyBenali** [comment]
My idea behind asking to submit it here was more to go towards a 2-way KYC integration option discussion for our platform in the future (for both buyers and sellers), as I think reselling is a whole different business model that has its own issues as well.

**Comment by w1kke** [comment]
That would also be an option. There was a discussion in the development telegram channel about free solutions for 2-way KYCs. But they always required the user to do a KYC with an official jurisdictional party to verify the identity. If the KYC itself is done by a company the service was not free e.g. Civic ( civic.com ).

It also complicates the whole process to get access a lot.

**Comment by pennachin** [comment]
As this conversation shows, this topic isn't primarily about the dapp software, it's about regulations, KYC and friends. So, again, please have this conversation in the community forum or elsewhere.
