### ISSUE TITLE
Users should have possibility to leave meaningful feedback (maybe short comment?).

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-betav1-dapp#228]
In current dApp users don't have possibility to communicate with service providers.

For example semantic segmentation service was down and I didn't know whom to communicate (even link to github repo was missing). 

For example we could have possibility to send a short message to service provider via email which should be specified in metadata.

**Comment by pennachin** [comment]
We should support something like that, but via the curation process rather than metadata, I think.

**Comment by raamb** [comment]
Couple of ways to do this
- Option 1 - Capture an email in the metadata to which the feedback is sent. As part of the curation we mandate that this field is populated. So feedback captured is sent to this email 
- Option 2 - We capture the feedback and store it in the marketplace service. We have a section in the DApp where the service provider can see feedback captured for their service. The authentication will be based on address used to access the DApp, if the address is the same as that of the service owner feedback is displayed.

**Comment by pennachin** [comment]
I strongly prefer option 1. What do others think?

**Comment by arturgontijo** [comment]
The downside here is that the email address will be available for everybody.
This could be a barrier to make it a good practice.
Maybe we should store it (email address or even a HTTP server) on the service side, like a key in the `snetd.config.json`.

**Comment by pennachin** [comment]
This is why I originally suggested using the curation process (which involves KYC anyway) instead of metadata...

**Comment by raamb** [comment]
> The downside here is that the email address will be available for everybody.
> This could be a barrier to make it a good practice.
> Maybe we should store it (email address or even a HTTP server) on the service side, like a key in the `snetd.config.json`.

We could have the daemon capture the email (in fact it already does). We could expose an API on the daemon that would return the email address to any user who has a channel open (as a security measure), the client can then send the message to this address. 
I dont think the daemon should take the responsibility of sending emails on its own.

**Comment by Vivek205** [comment]
New feedback section is added. Closing this issue.

**Comment by astroseger** [comment]
Am I right that feedback can be left only after successful call? 
If yes then what to do in case of malfunction in the service/daemon?

**Comment by raamb** [comment]
Feedback can be provided after call is completed, irrespective of whether
the call is successful or not.

Thanks,
Raam
