### ISSUE TITLE
ExampleService missing method list.

### ISSUE THREAD

**Issue by glauterpro** [singnet/snet-betav1-dapp#40]
**Describe the bug**
After openning a service interface, if you change of service more than one or two times, the list of methods is not populated anymore.

The browser doesn't find the event parameters:
https://github.com/singnet/snet-dapp/blob/81cdf0353007967e96288a69e913a8d0bc18a161/src/components/service/ExampleService.js#L71

https://github.com/singnet/snet-dapp/blob/81cdf0353007967e96288a69e913a8d0bc18a161/src/components/service/ExampleService.js#L77

I solved the problem by making the following change:
```
handleFormUpdate(event)
handleServiceName(event)
```

To get the list of methods populated again, I've changed the following line from:
https://github.com/singnet/snet-dapp/blob/81cdf0353007967e96288a69e913a8d0bc18a161/src/components/service/ExampleService.js#L83

To:
```
var data = Object.values(this.methodsForAllServices[strService]);
```

**To Reproduce**
1. Open any service interface
2. Select a service, then change to another service.
3. Try to see if the method list is populated.
4. you get an empty list.

**Expected behavior**
After changing a service, get the method list populated.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chromei]
 - Version [Version 71.0.3578.98 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
I suppose to get the same error on smartphones.

**Additional context**
The fix should be replicated to DefaultService component.

**Comment by raamb** [comment]
This issue has been resolved
