### ISSUE TITLE
Update in service metadata is not reflected in the DApp

### ISSUE THREAD

**Issue by raamb** [singnet/snet-betav1-dapp#43]
**Description**
Change in service metadata is not getting updated in the DApp.
From @arturgontijo
Last week I've updated my `zeta36-chess-alpha-zero`'s endpoint from `http://54.203.198.53:7077` to `http://54.203.198.53:7008`.
As the logs are showing, the DApp is getting the channel with the updated metadata but when I click on Invoke button, for some reason it's getting the outdated endpoint.

**Expected behavior**
DApp must use the updated service metadata

**Comment by arturgontijo** [comment]
The service's metadata is updated now.
We can close this.

**Comment by raamb** [comment]
Resolved by commit https://github.com/singnet/snet-marketplace-service/pull/27/commits/02f4216a21ebf216348c507205b43b1aa037a2f0 in marketplace service
