### ISSUE TITLE
Response from example service when returned succssfully shows a blank scree 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-betav1-dapp#45]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Dapp, select the DappOrg2 and click on the details button 
2. Click on invoke service , fill in the details to make a request to the Daemon 
3. response shows a blank screen 
4. ( see the console, which shows the response returned) 

**Expected behaviour**
Response returned from the service needs to be show in the result tab

**Comment by raamb** [comment]
This issue has been resolved now the DefaultService.js handles all cases
