### ISSUE TITLE
Call to the state service in Daemon before making the actual service call to the Daemon

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-betav1-dapp#46]
Amount from Client in header = Authorised Amount so far from Daemon + Price from Client
Make a GRPC call is to the Daemon state channel service to determine the authorized amount so far say (Y) 
(Y + price ) is what needs to be set on the header "PaymentChannelAmountHeader"

**Comment by raamb** [comment]
#131 fixes this
