### ISSUE TITLE
After deposit , page is stuck 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-betav1-dapp#55]
**Describe the bug**
Deposit money on the escrow channel, the page seems to be stuck 

![dapp](https://user-images.githubusercontent.com/45787863/51980136-27fbba80-24b5-11e9-8080-eda11f90f0a1.png)

**Comment by ferrouswheel** [comment]
Looks like this is error case for trying to deposit more than is in a user's wallet?
