### ISSUE TITLE
Multiple tags of a service cuts in to other columns 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-betav1-dapp#56]
**Describe the bug**
Refer to the screen shot below 

**To Reproduce**
PIck a service  with many tags 

![dappptags](https://user-images.githubusercontent.com/45787863/51980355-cee05680-24b5-11e9-85f9-cb284269baf7.png)

**Comment by ferrouswheel** [comment]
Now the tags wrap, but it's not nice to look at.

I think we should have a single row, and they shouldn't have as much wasted space (they should look more like stackoverflow tags), and they should be truncated after the first 3 (users could hover cursor to see the full list).

Even tho this is a Material design component, I feel it's not the right option and we'd be better off with plain text.

![image](https://user-images.githubusercontent.com/120327/52604594-570c2600-2ed0-11e9-9949-063bbb0d1213.png)
