### ISSUE TITLE
Use the expiry threshold from the service definition instead of a default

### ISSUE THREAD

**Issue by raamb** [singnet/snet-betav1-dapp#60]
Use the expiry threshold defined in the service metadata while suggesting expiry block number instead of using a default value.

**Comment by ferrouswheel** [comment]
It looks like the dapp is trying to this value, but I keep getting `payment channel is near to be expired, expiration time: 10305632, current block: 10303957, expiration threshold: 40320`.

I used Chrome's debugger, and it shows `this.serviceState['payment_expiration_threshold']` is null when trying to calculate the channel expiry. The rest of the metadata is there though :thinking:

**Comment by ferrouswheel** [comment]
I've tracked it down to the marketPlaceURL providing the null value.

Where is the source code for all the external urls the dapp relies on?

**Comment by raamb** [comment]
singnet/marketplace-service has the code. On which service are you facing this issue?

**Comment by ferrouswheel** [comment]
snet/translation on kovan.

But while looking at the data I saw others with a null payment expiry time
too.

**Comment by prashantramangupta** [comment]
For org_id **snet** and service_id **translation**, I am getting expiration as 0 from blockchain when I checked from ether wallet.

**Comment by ferrouswheel** [comment]
Doesn't the expiration come from service metadata? It shows `40320` for me when using kovan.

```
$ snet service print-metadata snet translation
{
    "version": 1,
    "display_name": "translation",
    "encoding": "proto",
    "service_type": "grpc",
    "payment_expiration_threshold": 40320,
    "model_ipfs_hash": "QmPUrqcezrR5ZDKDCW7fA9QTdczMHNzyrTFa4dFCnNQaiw",
    "mpe_address": "0x39f31Ac7B393fE2C6660b95b878FEB16eA8f3156",
    "pricing": {
        "price_model": "fixed_price",
        "price_in_cogs": 10
    },
    "groups": [
        {
            "group_name": "default_group",
            "group_id": "cKQBPXqInGo3BDSBGEi2oXjiX4hpjKJ50aBEvC7dxeg=",
            "payment_address": "0x464c564e427fA7A715922D9E0373a5D90589E021"
        }
    ],
    "endpoints": [
        {
            "group_name": "default_group",
            "endpoint": "http://34.216.72.29:6208"
        }
    ]
}
```

**Comment by prashantramangupta** [comment]
My bad, I took payment_expiration_threshold as channel expiration. 
Issue is resolved now.We have a consumer that populates an index based on events from the blockchain. Looks like we had a gap where these events were not processed. We have now rerun the consumer and data is populated. We also have a check in place to prevent this in future.

**Comment by raamb** [comment]
Dapp now reads expiration threshold from the service metadata.
