### ISSUE TITLE
Service is up, but down on the Dapp

### ISSUE THREAD

**Issue by glauterpro** [singnet/snet-betav1-dapp#70]
**Describe the bug**
The sentiment-analysis service is up and working fine when calling from CLI, but on the Dapp the status is down, hence it locks the user interface.

**To Reproduce**
1. Check the service calling by CLI: 
```
snet client call 294 0 54.203.198.53:7010 Analyze '{"value": "VGhpcyBpcyB2ZXJ5IHZlcnkgYmFkIGFjdGlvbg=="}'
```
2. Check the status on the Dapp and try to call.
3. You'll get the user interface locked.

**Comment by raamb** [comment]
Related to curation. Services are not auto available on the DApp. Once curated they are visible.
