### ISSUE TITLE
Escrow deposit seems to complete twice?

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-betav1-dapp#73]
I deposited money in escrow. Metamask showed me two transactions to confirm.

If this is correct, it would be good to give the user notice that they should expect two transactions.

After the transactions, the status message is duplicated:

<img width="601" alt="screenshot 2019-02-01 10 09 30" src="https://user-images.githubusercontent.com/120327/52085489-833ec180-2609-11e9-814c-86fc92c83a45.png">

**Comment by raamb** [comment]
The two transactions are to approve and to deposit. We had Approve as a separate step which people found confusing and hence we clubbed into one. 
The blockchain transactions nuances raises some very interesting nuances such as this. We have deliberately dumbed down the DApp to make it a little easier for people to understand but clearly we need to do a UX review and figure intuitive ways to educate people while the use it.

The duplicate message has been resolved

**Comment by ferrouswheel** [comment]
Tried to test this now.

![image](https://user-images.githubusercontent.com/120327/52181874-b5476200-285b-11e9-8499-e69ed8be4776.png)

Recent changes in metamask UI might be to blame, since background.js caused issues for me on Friday after they deployed an update.

**Comment by ferrouswheel** [comment]
Tested again and works okay :+1:
