### ISSUE TITLE
API based Search and Pagination

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-betav1-dapp#77]
Ideally I could share a url with 

http://localhost:8080/services#q=face

And it would automatically search for services that had "face" in the name.

(`q` for query)

**Comment by Vivek205** [comment]
# Search and Pagination

## Acceptance Criteria - 
*The italicised points are deferred for later release*
 1. User should be able to search with a keyword.
 2. The result should be populated while typing.
 3. *The user is provided with the options against which the search should happen (all, display Name, tags, orgId)* - deferred.
 4. *The option selected should be displayed in the input field as well; suffixed by a colon(<*field*>:<*keyword*>)(e.g.  displayname:sample).* - deferred.
 5. *The API includes the sorting option against a field* - defered
 6. *Should be able to sort in ascending as well as descending order* - deferred
 7. The search API should also include the provision for pagination (limit and offset).
 8. The pagination should happen for the current search criteria and also if search is empty.

## API Endpoint
**/search?q=example-service&s=all&limit=15&offset=0&sort_by=dn&order_by=desc**

 - **q** -  search keyword
 - **s** - field selected - all, dn(display name), tg(tags), st(status), pr(price), rt(ratings), org(organisation Id)
 - **limit** - no of results to be fetched
 - **offset** - no of results to be skipped
 - **sort_by** - field to be sorted 
 - **order_by** - order of sorting - ascending/descending

**Comment by ferrouswheel** [comment]
Note that my request was for a hash fragment to store the current search
details, not a new API/endpoint.

**Comment by raamb** [comment]
@ferrouswheel understood. We are however looking to support server side pagination and search as the standard way to go forward which will solve for what you are asking as well. Current search is on the browser side which is not a good option
