### ISSUE TITLE
Vote count on the list page does not auto-update after a vote has been casted on the job details page

### ISSUE THREAD

**Issue by raamb** [singnet/snet-betav1-dapp#82]
Vote count on the list page does not auto-update after a vote has been casted on the job details page

1. Invoke a service
2. Vote panel gets enabled
3. Cast your vote. The panel displays your vote
4. Close job details slide out. 
5. The vote count has not updated based on the vote

**Expected behavior**
The vote count on the listing page should display the new count immediately

**Comment by Vivek205** [comment]
Fixed along with the change #238
