### ISSUE TITLE
Search results should update pagination component

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-betav1-dapp#93]
The pagination component for services doesn't change based on the search results.

e.g. if I search for `face` on kovan I see my 4 services. However the pagination still shows four pages of results. If I click on page 2 it will show an empty list.

**Comment by anandrgitnirman** [comment]
This is fixed now 
![pagenationsearch](https://user-images.githubusercontent.com/45787863/52460075-95cb7480-2b8e-11e9-849b-b9a4f4bb9ef6.png)
